# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DOzlZJcJBo7BWf9GQweJMQb_-jaMAkEp
"""

from skimage import io, img_as_ubyte
from scipy import ndimage
import numpy as np
from matplotlib import pyplot as plt

from google.colab import files
uploaded=files.upload()

img=io.imread("WhatsApp Image 2023-04-22 at 00.09.03.jpeg")

print(img.shape)

img=img_as_ubyte(io.imread("WhatsApp Image 2023-04-22 at 00.09.03.jpeg",as_gray=False))

flippedLR=np.fliplr(img)

flippedUD=np.flipud(img)

plt.subplot(2,1,1)
plt.imshow(img, cmap="hsv")
plt.subplot(2,2,4)
plt.imshow(flippedUD)
plt.subplot(2,2,3)
plt.imshow(flippedLR)

rotated=ndimage.rotate(img,45)

plt.imshow(rotated)

uniform_fil=ndimage.uniform_filter(img,size=20)
plt.imshow(uniform_fil)

gauss_fil=ndimage.gaussian_filter(img,sigma=11)
plt.imshow(gauss_fil)

m_fil=ndimage.median_filter(img,2)
plt.imshow(m_fil)